# Generated by Django 4.2.5 on 2023-09-20 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urubanza', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name_plural': 'Club'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name_plural': 'Video'},
        ),
        migrations.RenameField(
            model_name='club',
            old_name='Client',
            new_name='client',
        ),
    ]
