# Generated by Django 4.2.5 on 2023-09-27 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('urubanza', '0003_delete_person_alter_options_alter_video_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Client',
            },
        ),
        migrations.RenameField(
            model_name='club',
            old_name='client',
            new_name='uwayishizemwo',
        ),
        migrations.AddField(
            model_name='video',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='urubanza.club'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='uwayishizemwo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urubanza.client')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urubanza.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
